name: social-network-backend
on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_TOKEN }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build jar
        run: ${{ secrets.BUILD_COMMAND }}
        id: build_jar

      - name: Cache docker image layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/social-network-backend
          cache-form: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Deploying to Digitalocean droplet
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.IP }}
          username: ${{ secrets.IP_USER }}
          password: ${{ secrets.IP_PASS }}
          port: 22
          script: |
            ${{ secrets.DEPLOY_COMMAND }}
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

